# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b71a0cfddab2da8bb3972dbdd69c6e43bfa56a866964b984cfbeb9444146be70b6bf069f9a3e5555f2d86c45c84e7d31de8e07848c45f0fb996ee675e3b9e76

test:
  secret_key_base: deb631e5212e210ddf09c964b0190d5ed8ff05866d579a51befed9b09c3a24bd5fe6d8f67b05abb56b7fe0ce91d9c384a965ddbdd96880959a877cbe58d298eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
